#pragma once

#include "CoreMinimal.h"
#include "Definations.generated.h"

USTRUCT()
struct FDialogContent
{
    GENERATED_BODY()
    FDialogContent() {};

    FDialogContent(const FString& InDialogScene) : DialogScene(InDialogScene) {}
    UPROPERTY()
    FString DialogScene;
};

USTRUCT()
struct FPersonInfo
{
    GENERATED_BODY()
    FPersonInfo() {}
    FPersonInfo(const FString& InName, const FString& InJob):
    Name(InName), Job(InJob){}
    UPROPERTY()
    FString Name;
    UPROPERTY()
    FString Job;
    
};
USTRUCT()
struct FPrompt
{
    GENERATED_BODY()
    UPROPERTY()
    FDialogContent DialogContent;
    UPROPERTY()
    TArray<FPersonInfo> Persons;
};

USTRUCT()
struct FAIServerData
{
    GENERATED_BODY()
    UPROPERTY()
    int32 statusCode;
    UPROPERTY()
    TArray<FString> messages;
};